spring:
  application:
    name: store

  datasource:
    url: jdbc:mysql://localhost:3306/store?useSSL=false&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
      hibernate:
          ddl-auto: update
      show-sql: true
      properties:
          hibernate:
          format_sql: true
